//
//  SecondViewController.swift
//  Tarot Dictionary
//
//  Created by Ryan Ball on 02/07/2017.
//  Copyright © 2017 Ryan Ball. All rights reserved.
//

import UIKit

class SecondViewController: UIViewController {
    
    let cardsArray = [Tarot(tarotName: "The Fool", tarotImage: UIImage(named: ("rwfool.png"))!, tarotDescription: "The Fool is numbered 0, the number of unlimited potential, and does not actually have a specific place in the sequence of the Tarot cards. The Fool can come either at the beginning of the Major Arcana or at the end. The Major Arcana is often considered as the Fool’s journey through life and as such, he is ever present and therefore needs no number.\n\n The Fool is shown at the beginning of his journey with unlimited potential. The sun rising up behind him represents the beginning of his journey. He is facing north-west, the direction of the unknown. He is looking upwards, toward the sky, or Spirit. He is about to step off a cliff into the material world but is he prepared? He has all the tools and resources he needs in the bag on his staff but he has not opened the bag yet. The white rose in his left hand represents purity and innocence. He has a guardian in the little white dog who will protect him throughout his journey but who will also push him to learn the lessons the Fool came here to learn. The mountains behind the Fool represent the realms of Spirit that he has just left and will spend his life trying to regain."),
                       Tarot(tarotName: "The Magician", tarotImage: UIImage(named: ("rwmagician.png"))!, tarotDescription: "The Magician is associated with the planet, Mercury and carries with it skill, logic, and intellect. The number of the Magician is one, the number of beginnings. The Magician is the bridge between the world of the spirit and the world of humanity. His right hand holds a staff raised toward the sky and his left hand points to the earth. He takes the power of the Universe and channels it through his own body and directs it to the physical plane. Above the Magician’s head is the symbol of eternity and around his waist is a snake biting its own tail, another symbol of eternity. His magical table holds all four suits of the Tarot, each of which represents one of the four primordial elements of the alchemists – earth, air, fire and water. These symbolise the appropriate use of mind, heart, body and soul in the process of manifestation. The Magician’s robe is white, symbolising the purity and innocence found in the Fool but his cloak is red, representing worldly experience and knowledge. In the bed of flowers at his feet this duality is repeated in the mix of pure white lilies and thorny red roses."),
                       Tarot(tarotName: "High Priestess", tarotImage: UIImage(named: ("rwhighpriestess.png"))!, tarotDescription: "The High Priestess is also known as Persephone, Isis, the Corn Maiden and Artemis. She sits at the gate before the great Mystery, as indicated by the Tree of Life in the background. She sits between the darkness and the light, represented by the pillars of Solomon’s temple, which suggests it is she who is the mediator of the passage into the depth of reality. The tapestry hung between the pillars keeps the casual onlookers out and allows only those initiated to enter. The pomegranates on the tapestry are sacred to Persephone. They are a symbol of duty (because Persephone ate a pomegranate seed in the underworld which forced her to return every year). The blue robe the Priestess is wearing is a symbol of knowledge. She is wearing the crown of Isis symbolising the Triple Goddess. The solar cross on her breast is a symbol of balance between male and female.\n\n In her lap, she holds the half-revealed and half-concealed Torah, representative of the exoteric and the esoteric teachings and higher knowledge. The moon under her left foot shows her dominion over pure intuition. The palm indicates fertility of the mind and the cube on which she sits is the earth. The planet associated with the High Priestess is the Moon."),
                       Tarot(tarotName: "The Empress", tarotImage: UIImage(named: ("rwempress.png"))!, tarotDescription: "The Empress is the archetypal Earth Mother, the Anima, the Feminine Principle, Demeter, Freyja and the Goddess of Fertility. Ruled by Venus, the planet of love, creativity, fertility, art, harmony, luxury, beauty and grace.\n\n The main feature of this card is the Empress herself, a full-figured woman with blond hair and a peaceful and calm aura about her. On her head she wears a crown of stars, showing her connection with the mystical realm of angels and fairies. She is dressed in a patterned robe of pomegranates, symbolic of fertility and is seated upon a luxurious array of cushions and flowing red velvet with the symbol of Venus emblazoned upon it.\n\n The Empress is surrounded by a beautiful, lush forest with a stream running through it, demonstrating the Empress’s deep emotional connection with Mother Earth and life. She draws her sense of peace from the trees and the water and is rejuvenated by the energy of nature. In the foreground, golden wheat springs from the ground, reflecting abundance from a recent harvest."),
                       Tarot(tarotName: "The Emperor", tarotImage: UIImage(named: ("rwemperor.png"))!, tarotDescription: "The Emperor is the complement to the Empress. He is the Masculine Principle, the Animus and the Patriarch. He represents power and authority, and his stern attitude is quite a departure from the sensual beauty of the Empress. The Emperor has a long, white beard, a symbol of his experience. As an archetype, it is common to see masculine figures of authority or father figures with long white beards. It suggests that this man has acquired years of wisdom and experience and he is worthy of listening to because he has seen first-hand the consequences of his actions.\n\n Behind his throne are barren mountains and the throne itself is decorated with four rams’ heads, representing intellectual heights, determination, action, initiative and leadership. The ram is also a symbol of Aries, the astral ruler of the Emperor. In his right hand, the Emperor holds an Ankh, the Egyptian symbol of Life, and in his left is an orb representing the world over which he rules. The orange background and the Emperor’s red clothing symbolise his passion and energy for life and the challenges it offers."),
                       Tarot(tarotName: "The Hierophant", tarotImage: UIImage(named: ("rwhierophant.png"))!, tarotDescription: "The Hierophant is known as the High Priest in some decks. He is the masculine counterpart to the High Priestess. He is also known as Chiron, the Pope and the Shaman. The Hierophant is ruled by Taurus.\n\n The Hierophant is represented by a religious figure, sitting within a formal church environment. He is wearing three elaborate vestments of his office that represent the three worlds. The crown he is wearing has three tiers to. His right hand is raised in benediction, the same hand the Magician has raised. While the Magician was taking raw power from the Universe and manifesting it on the material plane, the Hierophant channels that power through society (as in the religions of the world). The triple sceptre is another symbol of his dominion over the three worlds. The crossed keys represent a balance between the conscious and subconscious minds and unlock the mysteries. Before him kneel two initiates. The Hierophant’s task is to bring the two initiates into the church so that they can take up their appointed roles. This symbolises entry into all types of institutions where there is a shared group identity. These could include schools, clubs, teams, companies and societies."),
                       Tarot(tarotName: "The Lovers", tarotImage: UIImage(named: ("rwlovers.png"))!, tarotDescription: "The sign associated with the Lovers is Gemini. The two figures in the Lovers card are blessed and protected by the angel in the clouds above them. Angels, in general, represent the refinement of earthly desires. This angel, in particular, is Raphael, the angel of Air. One of the associations of Air is communication, necessary for a healthy relationship. The purple cloak on the angel represents royalty, a symbol of how important communication is. The sun shines brightly over the couple, bringing warmth and security. The earth at their feet is green and fertile and suggests life and happiness. The snake in the fruit-laden tree behind the woman suggests the story of Adam and Eve, the fall of humanity from grace, and the temptations of the world. The snake is also a symbol of the senses. The flames behind the man represent the flames of passion, indicating the primary concern of the man. There are twelve flames, representing the twelve zodiac signs, the symbol of time and eternity. The man looks to the woman, who looks to the angel, indicating the path of the conscious to the subconscious to the super-conscious, or from physical desire to emotional needs to spiritual concerns. The mountain is a phallic symbol, while the water is a feminine symbol, indicating balance between the two."),
                       Tarot(tarotName: "The Chariot", tarotImage: UIImage(named: ("rwchariot.png"))!, tarotDescription: "The Chariot is associated with the astrological sign of Cancer. He sits within a canopy of six-pointed stars, representing the celestial influences at work in this Tarot card. The crescent moons on the man’s shoulders are outward facing to refer to the formative world. The symbols on his tunic are alchemical symbols, representing the spiritual transformation of man. The square signifies earth, a sign of strength of will. The laurel and star crown indicate the highest attainment of man in spiritual evolution.\n\n The wings on the Chariot represent inspiration and the Hindu sign of the union of positive and negative. The black and white sphinxes have the same meaning. The Charioteer holds no reins, just the wand from the Magician card. He controls through strength of will in the same way the Magician does. The city is behind him, indicating he has turned his back on civilisation and materialism in order to seek spiritual matters."),
                       Tarot(tarotName: "Strength", tarotImage: UIImage(named: ("rwstrength.png"))!, tarotDescription: "Under a golden sky, a woman gently pats a lion on its forehead and lower jaw. The woman gazes down at the lion with a peaceful smile on her face and appears to be successfully taming this wild beast. The fact that Strength is represented by a woman indicates that this card is not focused on pure physical strength. She has the infinity symbol above her head, the same symbol seen in the Magician. Her white robe is that of the innocent Fool, indicating a purity of spirit. The blue mountain in the background is the same phallic symbol seen in the Lovers. The lion is a symbol of our animal passions and desires. The lion itself is sticking out his tongue. Animals that are preparing to bite do not stick their tongues out. This lion is happy to submit and surrender to the woman. The woman overcomes the lion with a quiet strength that can only come from within. Her left arm represents mental effort, while the right arm represents physical effort. Her right arm is merely holding, while the left arm is exerting all the pressure. She wears a belt and crown of flowers and stands unprotected in an open green field. The crown on her head represents the fullest, most beautiful expression of nature and transient life. The sign associated with the Strength card is Leo."),
                       Tarot(tarotName: "The Hermit", tarotImage: UIImage(named: ("rwhermit.png"))!, tarotDescription: "The Hermit stands alone on the top of a mountain with a lantern in his hand. Mountains typically symbolise achievement, growth, and accomplishment. The Hermit has attained his spiritual pinnacle and is ready to share his knowledge with others. He is also continuing the path he has chosen, committed to his goal of ultimate awareness. The star in the lantern is a six-pointed star (the Seal of Solomon, a symbol of wisdom). The staff carried by the Hermit is the patriarch’s staff, a symbol of the narrow path of initiation and an emblem of power and authority. It represents the Hermit’s ability to use his isolation and the knowledge he has gained as a tool upon his path to reach even higher levels of awareness. The staff is in the Hermit’s left hand, the hand associated with the subconscious mind. The snow at his feet represents the heights of spiritual attainment. He wears the grey cloak of invisibility. His secrets are not for everyone, only for those earnestly seeking them and those willing to climb the heights to wisdom. The astrological correspondence for this card is Virgo and the number 9 signifies accomplishment, wisdom, the attainment of goals, as well as the search for truth."),
                       Tarot(tarotName: "Wheel Of Fortune", tarotImage: UIImage(named: ("rwwheelfortune.png"))!, tarotDescription: "The Wheel of Fortune is highly symbolic. The angel in the top left corner is Aquarius, the eagle is Scorpio, the lion is Leo and the bull is Taurus. These are the four fixed signs of the Zodiac but all have wings signifying stability amidst movement and change. The book they each have in their hands is the Torah, representing wisdom. On the wheel itself are the Hebrew letters IHVH (Yod Heh Vau Heh), the unpronounceable name of God. Interspersed with these letters are TORA (read anti-clockwise) or TARO (read clockwise) which also translates to TAROT when you return to the spot where you started. The snake descending on the left side of the Wheel is the Egyptian god Typhon, the god of evil. The snake also represents the life force descending into the material world. The Anubis rising on the right side of the Wheel is Hermes, a symbol of intelligence, wisdom ascending or our shadow selves. The Sphinx on the top of the wheel represents life’s riddles. The middle wheel contains the alchemical symbols for mercury, sulphur, water and salt – the building blocks of life and the four elements – and represents formative power. The outer circle represents the material world. The eight spokes in the wheel represent the Universal radiant energy, as well as the eight Sabbats of the year. The blue background represents wisdom.\n\n The planet of this card is Jupiter, the planet of opportunity, growth, success, and expansion. The number 10 is a higher octave of the number 1, empowering the qualities of the 1."),
                       Tarot(tarotName: "Justice", tarotImage: UIImage(named: ("rwjustice.png"))!, tarotDescription: "Justice is ruled by Libra and the card number is 11. The figure of Justice sits in her chair, cloaked in red and holding a sword in her right hand and scales in her left. She wears a crown with a small square on it representing well-ordered thoughts. Notice the clasp holding the cloak together. The square is the law protecting the circle and the eternal state of oneness within us all. The sword is double-edged, cutting both ways, signifying impartiality. It is point-up, signifying victory. The sword in her right hand demonstrates the logical, well-ordered mindset necessary to dispense fair justice. The scales are in her left, intuitive hand, showing that logic must be balanced by the intuition. A little white shoe pops out from beneath her cloak, reminding us of the spiritual consequences of our actions. The purple cloth draped behind her signifies compassion and the grey pillars represent the constraints of the physical world."),
                       Tarot(tarotName: "The Hanged Man", tarotImage: UIImage(named: ("rwhangedman.png"))!, tarotDescription: "The Hanged Man shows a man suspended, upside-down, from the living World Tree, rooted in the underworld and supporting the heavens. Given the serene expression on his face, it is believed he is hanging on the tree of his own will. His right foot is bound to the tree but his left foot remains free, bent at the knee and tucked in behind his right leg. His arms are bent, with hands held behind his back, forming an inverted triangle. The man is wearing red pants representing human passion and the physical body, a blue coat for knowledge, and yellow shoes representing his high ideals. Around the Hanged Man’s head is a bright yellow halo showing spiritual attainment, with the grey background suggesting invisibility (a good reminder to not flaunt your spirituality). This is the card of ultimate surrender, of being suspended in time and of martyrdom and sacrifice to the greater good. This is the archetype to meditate on to help break old patterns of behaviour and bad habits that restrict you.\n\n The Hanged Man’s number is 12 – a higher octave of the number 3, representing careful planning and orderly growth leading to spiritual development. 1 (beginning) + 2 (the reasoning force) = 3 (the product of rebirth). The ruling planet is Neptune, the planet of self-sacrifice and idealism."),
                       Tarot(tarotName: "Death", tarotImage: UIImage(named: ("rwdeath.png"))!, tarotDescription: "The Death card shows Death himself riding on a white horse, holding a black and white flag. Death is portrayed as a skeleton as the skeletal bones are the part of the body that survives death. The armour he is wearing indicates that he is invincible and unconquerable. Indeed, no-one has yet triumphed over death. The horse that Death rides is white, the colour of purity. Death is therefore the ultimate purifier. All things are reborn fresh, new and pure. Notice even the bishop paying homage to him. All sectors of the human race are represented here – men, women and children – showing that Death does not discern between age, race or gender.\n\n The banner that Death carries has a black background, indicating an absence of light. The white rose, on the other hand, indicates beauty, purification and immortality. In the background of the card, there is a rising sun, a sign of immortality. The sun appears to ‘die’ each night but is reborn fresh and new every morning. The two pillars are guarding the gateway to the sun, symbolising the knowledge needed to gain immortality. The boat on the water in the background is the ferry that transports the souls across the River Styx. The background is a neutral grey, again showing Death’s impartiality.\n\n Death is ruled by Scorpio (the sign of ‘sex, death and taxes’) and the number is 13, sacred to the Goddess as there are thirteen moons in a year."),
                       Tarot(tarotName: "Temperance", tarotImage: UIImage(named: ("rwtemperance.png"))!, tarotDescription: "On the Temperance card stands a winged angel. The angel is actually a hermaphrodite (the child of Hermes and Aphrodite), showing a balance between the genders. The angel has one foot on dry land, representative of the material world, and one foot in the water, representative of the subconscious. In this position, she also represents the need to ‘test the waters’ before jumping headfirst into unknown circumstances. Here she tempers the whimsical flight of the Fool who jumps without giving a second thought. The triangle inside the square on her robe represents the female being protected by natural law. In her hands she holds two cups which she uses to mix water. The cups represent the sub- and super-conscious minds. One cup can be thought of as holding hot water and the other cold water. The water flowing between them is actually going from the lower cup to the higher one, signifying rising from a lower plane to a higher one. The temperate individual mixes the opposites and finds a balance in life by avoiding extremes. The astrological sign is Sagittarius, the teacher of truth, enthusiasm, tolerance and beauty."),
                       Tarot(tarotName: "The Devil", tarotImage: UIImage(named: ("rwdevil.png"))!, tarotDescription: "The card of the Devil portrays a Satyr, a creature that is half man and half goat. In many myths, the goat was considered an unclean and lustful animal. However, the goat also symbolises the scapegoat, the person or thing upon which people project the inferior side of themselves in order to feel better about themselves. Thus the Devil is the scapegoat we blame for our troubles in life.\n\n The Devil has the wings of a vampire bat, an animal that sucks the life blood out of its prey. This is symbolic of what happens when we give full reign to the realm of our raw desires. We lose our vitality and life energy. The Devil has an almost hypnotic stare, bringing those who come near him within his power. Above him is an inverted pentagram, signifying the darker side of magic and occultism.\n\n At the foot of the Devil stands a man and a woman, both naked and chained to the podium on which the Devil sits. They appear to be held here, against their will, but only closer observation, the chains around their necks are loose and could be easily removed. This symbolises that bondage to the Devil is ultimately a voluntary matter which consciousness can release. The man and woman wear tiny horns like those of the Satyr – they are becoming more and more like the devil the longer they stay here. Both have tails – a further symbol of their animalistic or 'lower' tendencies.\n\n The dark and doorless cave implies that the Devil dwells in the most inaccessible realm of the unconscious and only crisis can break through the walls.\n\n The number 15 in numerology equals 6, the number that corresponds to the Lovers, and here the lovers are shown chained, in bondage to the material, sensual side of their nature. This card is ruled by Capricorn, the goat."),
                       Tarot(tarotName: "The Tower", tarotImage: UIImage(named: ("rwtower.png"))!, tarotDescription: "The Tower shows a tall tower pitched atop a craggy mountain. Lightning strikes and flames burst from the building’s windows. People are seen to be leaping from the tower in desperation, wanting to flee such destruction and turmoil. The Tower signifies darkness and destruction on a physical scale, as opposed to a spiritual scale. The Tower itself represents ambitions built on false premises. The lightning bolt breaks down existing forms in order to make room for new ones. It represents a sudden, momentary glimpse of truth, a flash of inspiration that breaks down structures of ignorance and false reasoning. Notice the lightning bolt is oriented left to right (from the perspective of the card), from heaven to earth, and from Spirit to material. The falling figures correspond to the chained prisoners in the Devil card. They fall headfirst, because the sudden influx of spiritual consciousness represented by the lightning flash completely upsets all our old notions about the relations between subconsciousness and self-consciousness. The flames are actually the Hebrew yods. There are 22 flames, representing the 22 Major Arcana. The gray clouds are the clouds of misfortune that rain on everyone indiscriminately. The ruling planet of this card is Mars."),
                       Tarot(tarotName: "The Star", tarotImage: UIImage(named: ("rwstar.png"))!, tarotDescription: "The Star card shows a naked woman kneeling at the edge of a small pool. The woman holds two containers of water. She pours the water out to nourish the earth and to continue the cycle of fertility, represented by the lush greenery around her. The other container pours the water onto dry land in five rivulets, representing the five senses. The woman has one foot on the ground, representing her practical abilities and good common sense, and the other foot in the water, representing her intuition and inner resources, and listening to her inner voice. Behind her, shines one large star and seven smaller stars, representing your chakras. This represents a need to open your chakras and cleanse your aura. Notice all the stars have eight points. The Star is associated with the number 17, which equals 8 (1+7=8). Eight is Strength, the quality needed to accept your faults and love yourself in spite of them. The bird in the tree in the background is the sacred ibis of thought, roosting in the tree of the mind. The astrological sign of the Star is Aquarius."),
                       Tarot(tarotName: "The Moon", tarotImage: UIImage(named: ("rwmoon.png"))!, tarotDescription: "The Moon is the card of intuition, dreams and the unconscious. The Moon provides light as a reflection of the Sun, yet this light is dim, uncertain, and only vaguely illuminates our path as we journey toward higher consciousness. The pool at the base of the card represents the subconscious mind and the crayfish that crawls out of the pool symbolises the early stages of consciousness unfolding. This creature also represents the often disturbing images that appear from our inner depths, just as the dog and wolf at the beginning of the path represent the tamed and the wild aspects of our minds. The path leads between two towers into the mountains in the distance, showing the way to the unconsciousness. The astrological sign associated with this card is Pisces – psychic, receptive and mysterious."),
                       Tarot(tarotName: "The Sun", tarotImage: UIImage(named: ("rwsun.png"))!, tarotDescription: "The Sun is an image of optimism and fulfilment, the dawn that follows the darkest night. As the source of all life on earth, the Sun represents the source of life itself. The child playing joyfully in the foreground represents the happiness of our inner spirit when we are in tune with our truest Self. He is naked, having nothing to hide. He has all the innocence and purity of childhood. The white horse upon which the child rides represents strength and purity of spirit. The horse is without a saddle and is controlled without the use of the hands. This is a symbol of perfect control between the conscious and subconscious. The child holds an orange banner in his left hand, showing that control has passed from the conscious to the subconscious. The orange banner represents action and vibration, and the rays of the sun represent the same thing. The straight rays are action while the wavy rays represent vibration. The sunflowers in the background represent life and the fruitfulness of the spirit under the nourishment of the Sun. There are four sunflowers, representing the four suits of the Minor Arcana, as well as the four elements. The astrological correspondence to this card is the Sun, of course."),
                       Tarot(tarotName: "Judgement", tarotImage: UIImage(named: ("rwjudgement.png"))!, tarotDescription: "The Judgement card shows a number of naked men, women and children rising up from their graves, arms outspread and responding to the trumpet call of the archangel, Gabriel, who hovers high above them. The people are appealing to the angel, ready to be judged by the power of the Universe. In the background, there are huge mountains, or even tidal waves, which signify insurmountable obstacles and the impossibility of avoiding judgment. The ocean represents the end of the river that flows through the Major Arcana, starting with the Empress. Gabriel’s banner is red on white, the same as the Magician’s clothing. As with everything in life, the beginning is woven irrevocably into the end and the end eventually leads to a new beginning. The planetary ruler of this card is Pluto, the ruler of the underworld."),
                       Tarot(tarotName: "The World", tarotImage: UIImage(named: ("rwworld.png"))!, tarotDescription: "In the centre of the World is a dancing figure, rejoicing in the completion of the journey and celebrating not only this completion but also the new beginnings it promises. The dancer has one leg crossed over the other, just like the Hanged man. She is, in a sense, his opposite (i.e. the Hanged Man upright). As the Hanged Man looks infinitely inward, the dancer in the World card looks infinitely outward. In each of her hands she holds a wand or baton, representative of evolution and balance. She is surrounded by a thick, green wreath, symbolic of success, victory, achievement and accomplishment, and tied with the red ribbons of eternity. The red ribbons form the infinity symbol, representing the infinite rewards of positive effort in improving both ourselves and those around us. Within the laurel wreath are stars of light indicating attainment of enlightenment or cosmic consciousness.\n\n The figures in each of the four corners of the World card are the same figures that appear on the Wheel of Fortune. Interestingly, the World card is very much associated with the Wheel of Fortune, reflecting the cyclical progression of time and the human experience. The four figures (a lion, bull, cherub and eagle) represent the four fixed signs of the zodiac – Leo, Taurus, Aquarius and Scorpio. These are symbolic of the four elements, four suits of the Tarot, four compass points, four seasons, and the four corners of the universe. And all are within the dancer’s sight and power. The planetary ruler is Saturn, the symbol of time."),
                      
                      
                      Tarot(tarotName: "Ace Of Cups", tarotImage: UIImage(named: ("rwacecups.png"))!, tarotDescription: "The Ace of Cups shows a hand holding a cup or chalice that is overflowing with five streams of water. The hand that appears from the clouds represents our consciousness of spiritual energy and influence. Radiating from the hand are rays which symbolises that you must always trust your inner feelings and your heart to lead the way. This is your intuition and inner power talking to you. The five streams represent the abundance and power of the spirit and the effect of spiritual energy upon our five senses. A dove holding a wafer or small disc in its mouth descends from above, signifying the incarnation and appearance of the spirit in the material world. Below the hand is a great sea covered with lotus blossoms, symbolising the awakening of the human spirit. The cup has an upside down M or a W inscribed on it."),
                       Tarot(tarotName: "Two Of Cups", tarotImage: UIImage(named: ("rw02cups.png"))!, tarotDescription: "The Two of Cups depicts a man and a woman exchanging cups in what appears to be a wedding ceremony with the caduceus of Hermes between them. The two-snake caduceus design has ancient and consistent associations with trade, negotiation, balance, duality (union of opposites), proper moral conduct, protection and cosmic energy. On the Two of Cups, the caduceus sends a positive message for new partnerships, and suggests that with honour, respect and balance, new relationships shall be rewarding. At the top of the caduceus is a lion’s head, a symbol of passion and fire energy suggesting that there may be a lot of sexual attraction between the people, although that may or may not be allowed to express itself. The two snakes that wind up the caduceus represent dark and light and their coexistence within us."),
                       Tarot(tarotName: "Three Of Cups", tarotImage: UIImage(named: ("rw03cups.png"))!, tarotDescription: "The Three of Cups is a card of celebration and accomplishment. Three young maidens dance in a circle with their golden goblets upraised in a toast of joy. Their arms reach out to each other and they connect through their emotions and their friendship with one another. The ground is covered with fruit and there is a general sense of abundance and happiness. Each woman in the Three of Cups has a wreath of laurel on her head. Wreaths of this type have long been a symbol of victory and success. A sweet smelling laurel wreath is also a symbol of protection, peace and purification and is a message that the favour of the Universe is upon us, and that we shall be the victor in this stage of our lives. At the women’s feet lie various flowers, symbolising joy, beauty, compassion and growth. The flowers remind us of the good times in life, the sweet smell of success, and the beauty that surrounds us if only we open up to its presence."),
                       Tarot(tarotName: "Four Of Cups", tarotImage: UIImage(named: ("rw04cups.png"))!, tarotDescription: "The Four of Cups depicts a young man sitting under a tree far away from others in what looks like deep contemplation and meditation. In fact, he is so engrossed in deep contemplation that he does not appear to notice the cup being presented to him by an outstretched arm. A further three cups stand at his feet, symbolising the world and its attractions but again, he pays little attention to these. In this sense, he indicates the need to look deep into our Self to discover the answers we seek. External influences can be distracting and may not lead us to the goal we seek even if those influences purport to be of a spiritual nature.\n\n This young man and his predicament suggest the story of the Buddha under the Bodhi Tree, contemplating the state of the Universe and unwilling to rise until he has reached the Truth. He is not taking the cup and indeed appears to be paying no attention to it whatsoever. He misses this gift of love and opportunity because he’s completely tuned within."),
                       Tarot(tarotName: "Five Of Cups", tarotImage: UIImage(named: ("rw05cups.png"))!, tarotDescription: "The Five of Cups is a card that signifies difficulty, loss, and the challenges of dealing with that loss. The figure in the card wears a black cloak in which he hides his face in apparent despair. At his feet are five cups, three of which have fallen and spilled onto the ground and the other two behind his back remain standing. He does not seem to notice these upstanding cups because he is so focused on the fallen cups instead. Ahead of him a powerful river flows between himself and a castle or home in the distance. To his right is a bridge that can lead him to the security of the house across the river. Despite the fact that this card has a strong indication of loss and tribulation, there is a positive aspect that must be considered. Is your cup half full or half empty?"),
                       Tarot(tarotName: "Six Of Cups", tarotImage: UIImage(named: ("rw06cups.png"))!, tarotDescription: "On the Six of Cups, there are six cups filled with white, five-pointed flowers. A young boy seems to smell one flower, offering this filled cup to another young child. The small child symbolises the past and the taller child symbolises the future, and together they symbolise happy reunions with past friends or lovers. They share old pleasures with lots of nostalgia. In the background, there is an older figure walking away, symbolising our worries leaving us to be locked in the turret. The house symbolises comfort and security but the barren garden symbolises the lost happier times of the past. Everything is bright yellow which indicates great happiness in this overall scene."),
                       Tarot(tarotName: "Seven Of Cups", tarotImage: UIImage(named: ("rw07cups.png"))!, tarotDescription: "The Seven of Cups depicts an individual faced with the mysterious appearance of strange images from cups in a floating cloud. Clouds conjure ideas, dreams, thoughts, illusions, transitions and mystery. Though the character’s back is toward us, we can see from the half-raised arm-gesture that the apparitions before him are something of a surprise. The various prizes appearing from the cups are a mixture of positive and negative visions. These cups each have a single item rising from them – a snake, representing wisdom and knowledge; a shrouded figure, representing the need for illumination; a human head, representing a companion for the conjurer; a tower, representing stability and power; treasure, representing abundance and wealth; a laurel wreath, representing victory or honour, and status; and a dragon, representing supernatural forces. The character faced with these spectres is taken aback by their confusing nature. Although the seven cups appear as gifts or prizes, there is always danger hidden within one or two of them to sting anyone who ventures near. What this suggests is that sometimes you have to choose between many options, all of which may be tempting but only one of which is the best choice. At others times not all of those choices are real options at all; they are delusions of the imagination."),
                       Tarot(tarotName: "Eight Of Cups", tarotImage: UIImage(named: ("rw08cups.png"))!, tarotDescription: "The Eight of Cups is a card of change and transition. The card evokes an immediate reaction of sadness and a sense of solitude. The young man in this card has turned his back on all he has accumulated or accomplished before. He disappears by night into a barren and difficult terrain with only a cloak on his back and a staff in hand. The character in the Eight of Cups has lived and experienced life’s joys and sorrows. His journey is undertaken because of a sense of restlessness and unhappiness experienced as the result of achieving all he has desired, yet finding those things to be less fulfilling than expected. This individual has chosen to forsake the familiar and the comfortable in the pursuit of higher goals. He is embarking upon the spiritual journey because he has not found deep satisfaction in the things of the world, the things with which he is familiar."),
                       Tarot(tarotName: "Nine Of Cups", tarotImage: UIImage(named: ("rw09cups.png"))!, tarotDescription: "In Nine of Cups, a portly, middle-aged man sits upon a wooden bench with his arms crossed in contentment. He is dressed smartly and wears an expression of true satisfaction on his face and his red head-dress symbolises an active mind. Behind him is a wall with nine golden cups arranged in a structured, well-organised arch. The man enjoys success both materially and spiritually and represents the fulfilment realised after the accomplishment of our deepest desires."),
                       Tarot(tarotName: "Ten Of Cups", tarotImage: UIImage(named: ("rw10cups.png"))!, tarotDescription: "On the Ten of Cups we see a loving couple united by the bonds of true, everlasting love. They not only have each other but all that they wish for in life as well, represented by the two children frolicking at their side and the small but comfortable home in the distance, surrounded by trees and water. The family home symbolises stability and homely comforts, while the green garden symbolises fertility and the river symbolises a free flow of feelings. A rainbow of cups is overhead, blessing the scene. The cups symbolise an abundance of heavenly gifts and the rainbow signifies the end of hard times and is also is considered to be a highly spiritual omen in many of the world’s religions. It is a sign that the idyllic scene we see represented has been blessed from above and reinforces the idea that the achievement of perfect love is one sure way of experiencing the glory of the heavens here on earth."),
                       Tarot(tarotName: "Page Of Cups", tarotImage: UIImage(named: ("rwpagecups.png"))!, tarotDescription: "The Page of Cups, like the Pages in all the suits, represents some sort of beginning or renewal. The Page of Cups is dressed in a blue tunic with floral print all over it and sports a bohemian type of beret on his head with a long, flowing scarf attached to it. The young man stands alone on the seashore with a single golden cup in his hand. Surprisingly, a fish pops its head out of the cup and looks at the young man. The young man simply expects to raise his cup for a toast or a drink, and instead is confronted with the ominous appearance of a fish, which even appears to be speaking to him. The Page of Cups indicates the surprising and unexpected nature of inspiration that comes to us from the realm of the unconscious and the spirit. Inspiration is seen to be something which comes upon us most unexpectedly and often in a manner which we do not understand."),
                       Tarot(tarotName: "Knight Of Cups", tarotImage: UIImage(named: ("rwknightcups.png"))!, tarotDescription: "The Knight of Cups is seen as a young knight, riding along on his white horse, holding a cup as if he is a messenger of some type. Unlike the Knight of Wands or the Knight of Swords, the Knight of Cups is not charging along but rather his horse moves slowly forward, giving an impression of calmness and peace. The horse represents power, energy, and drive, and of course the colour white is a symbol of purity, spirituality, and light. The Knight wears a cloak covered with images of fish, the symbol of the spirit, consciousness and creativity. His helmet and feet are winged, a symbol of an active and creative imagination."),
                       Tarot(tarotName: "Queen Of Cups", tarotImage: UIImage(named: ("rwqueencups.png"))!, tarotDescription: "The Queen of Cups is the Queen of the realm of emotions. She is a beautiful, introspective woman who sits on a throne at the edge of the sea. In her hands, she cradles a beautiful cup with handles shaped like angels. The cup is closed, an indication that the thoughts of the Queen originate from the unconscious, from the depths of her own soul. Wearing a gold crown and silver robe, she is alone, sitting and staring at this cup, which she holds before her with both hands on the base. The stone throne upon which she sits is decorated with images of sea-nymphs, fish, and scallop shells. The sea and fish are symbols of the unconscious mind and water in general represents emotion, spirit, and feeling. The cloudless bright blue sky and placid water of the sea surround her. Her feet do not touch the water; they rest comfortably on colourful rocks washed up in front of her."),
                       Tarot(tarotName: "King Of Cups", tarotImage: UIImage(named: ("rwkingcups.png"))!, tarotDescription: "The King of Cups sits on his throne on a grey stone block, calmly in the midst of a turbulent sea and wears a necklace with a fish amulet. The fish is the symbol of spirit and creativity and represents the balance of the unconscious with the conscious. Behind him on his right, another fish jumps wildly from the tumultuous ocean, and, on his left, a ship sails steadily in the choppy ocean. These images are a sign that the unconscious has been allowed to break through and has been recognised by the King, yet it remains within his power and does not overwhelm him. The King of Cups does not repress his emotions and unconscious impulses but has learned to accept and deal with them in a mature and balanced manner."),
                      
                      
                      Tarot(tarotName: "Ace Of Pentacles", tarotImage: UIImage(named: ("rwacepentacles.png"))!, tarotDescription: "The Ace of Pentacles depicts a single hand with a pentacle coming out of the clouds, much like the Aces of the other suits. And, again like the other Aces, the landscape below the ‘hand of heaven’ represents the primary element of the suit. In the Ace of Pentacles, the landscape is a rich garden with flowers, shrubs, a flowing creek and mountains in the distance, indicating prosperity, growth and wealth."),
                       Tarot(tarotName: "Two Of Pentacles", tarotImage: UIImage(named: ("rw02pentacles.png"))!, tarotDescription: "On the Two of Pentacles, a young man dances as he juggles his worldly concerns. The infinity sign loops around the two Pentacles suggesting that he can handle unlimited problems. In the background, two ships ride the waves easily, cruising the ups and downs of life. The man seems to have a somewhat concerned look on his face, yet he dances with apparent abandon despite the turbulence of the sea behind him."),
                       Tarot(tarotName: "Three Of Pentacles", tarotImage: UIImage(named: ("rw03pentacles.png"))!, tarotDescription: "The Three of Pentacles shows a young apprentice working in a cathedral. In front of him stand two architects who are holding the plans for the cathedral. The apprentice appears to be discussing his progress so far with two architects and even though he is less experienced, the architects listen carefully as they value his opinion and his specialist knowledge. There is also an acknowledgement that this young man is an essential contributor to the completion of the cathedral and the architects want to make sure that everyone is on the same page."),
                       Tarot(tarotName: "Four Of Pentacles", tarotImage: UIImage(named: ("rw04pentacles.png"))!, tarotDescription: "The Four of Pentacles shows a man sitting on stool, away from his home town. He tightly holds onto his pentacles or coins in a very defensive posture as though he were hoarding them for fear of loss. One pentacle is balanced on his head, one clutched between his hands, and two are securely placed underneath his feet. He is making sure that no-one touches his coins! And, he cannot go anywhere because his feet are busy holding the coins down. In other words, this man is so tied up with his possessions, that he cannot do anything else. His eyes appear darkened from hard work but his mouth betrays the hint of a smile, which comes from the self-satisfaction of his accomplishments."),
                       Tarot(tarotName: "Five Of Pentacles", tarotImage: UIImage(named: ("rw05pentacles.png"))!, tarotDescription: "The Five of Pentacles, like the fives in the other suits, portrays a situation of adversity. In this card, a destitute couple walk through the snow outside the stained glass of a brightly lit church window. The church is symbolic of providing spiritual comfort while helping those who cannot help themselves. The man uses a crutch because of his crippled leg and the woman attempts to cover herself with her threadbare shawl. Both appear to be living in poverty and with little or no possessions."),
                       Tarot(tarotName: "Six Of Pentacles", tarotImage: UIImage(named: ("rw06pentacles.png"))!, tarotDescription: "The Six of Pentacles shows a man dressed in a purple robe, symbolic of his wealth and status. In one hand, he holds a balanced scale, representing fairness and equality, and with the other hand, he feeds two beggars who kneel at his feet. Not only does this card reflect the state of being materially secure, it also suggests that you are able to use the abundance in your life for the benefit of others. The wealthy man shares his abundance so that stability is preserved."),
                       Tarot(tarotName: "Seven Of Pentacles", tarotImage: UIImage(named: ("rw07pentacles.png"))!, tarotDescription: "The Seven of Pentacles portrays a young man taking a rest from the difficult work of harvesting his abundant crop. He has been labouring long and hard in his garden. The foliage is full and the blossoms are out. It seems that his work has paid off. He gazes meditatively at the pentacles hanging from the rich greenery of the thicket in which he works and seems to be contemplating the value of his efforts. He is finally taking a break to admire his handiwork and the benefits of his labour."),
                       Tarot(tarotName: "Eight Of Pentacles", tarotImage: UIImage(named: ("rw08pentacles.png"))!, tarotDescription: "The Eight of Pentacles shows a young man labouring over eight coins, carefully etching out a pentacle shape into each coin. He has already successfully completed six coins, and has two more to go. It is clear that he is in the middle of a project that absorbs all his attention. He has isolated himself from others (the town in the background) in order to concentrate on the task at hand. This card reflects a time when you are focusing all of your energy on something and making sure it is as perfect as it can be. You are very engaged in what you are doing and determined to do a good job."),
                       Tarot(tarotName: "Nine Of Pentacles", tarotImage: UIImage(named: ("rw09pentacles.png"))!, tarotDescription: "The Nine of Pentacles shows a mature woman walking in the midst of a vineyard. The vines are heavy with grapes and golden coins representing the fruitful accomplishment of all her desires. A falcon sits calmly on her left hand, symbolising her own intellectual and spiritual self-control. Far in the background is a large house, presumably belonging to the woman herself. There is a general sense of peace, satisfaction, and the fulfilment of a creative venture or personal investment in the image of the Nine of Pentacles that offers a more permanent, lasting achievement as the result of one’s own efforts."),
                       Tarot(tarotName: "Ten Of Pentacles", tarotImage: UIImage(named: ("rw10pentacles.png"))!, tarotDescription: "The Ten of Pentacles is a card of culmination and final fulfilment. The card shows an aged, wise man sitting comfortably just outside an archway leading into a town. He is surrounded by his family and his dogs and wears a rich robe decorated with images of grapevines, crescent moons, and other symbols. Behind the laughing couple under the arch, a young boy reaches playfully to pet one of the dogs. This card is a symbol of financial security, accomplishment, and comfort. The patriarch is able to rest and enjoy the fruits of his labours in retirement while he looks on at the lives of his children and grandchildren. This is a man who has accomplished a great deal during his life and is now able to rest in the satisfaction of knowing that what he has created will provide value and joy to others, even when he is gone."),
                       Tarot(tarotName: "Page Of Pentacles", tarotImage: UIImage(named: ("rwpagepentacles.png"))!, tarotDescription: "The Page of Pentacles shows a young man who stands alone in a field full of freshly blossoming flowers. Behind him in the distance to his right is a grove of lush trees, probably fruit-bearing trees of some sort, and to his left lies a newly furrowed field which promises an abundant harvest. The Page walks slowly as though he were unaware of anything around him other than the golden coin in his hands, which he closely examines. The bright sky above him suggests that all is well in his world and that this is a tranquil moment spent planning his path towards future success.\n\n The Page of Pentacles, like the pages of all the suits, is a card of new beginnings, of inspiration and the initial stages of a creative project or venture. Pentacles correspond to the alchemical element of earth, and in this sense the coin that the Page holds may symbolise the beginnings of sensual awareness not only in terms of money and its value but also in terms of a growing awareness of the importance of health and other material needs."),
                       Tarot(tarotName: "Knight Of Pentacles", tarotImage: UIImage(named: ("rwknightpentacles.png"))!, tarotDescription: "The Knight of Pentacles, like the Knights of the other suits, represents work, effort, and the responsibility that follows upon the dreams of the Page. The Knight of Pentacles sits upon a heavy plough horse in the midst of a field. In his hands he carries a single gold coin. His eyes reflect careful thought and consideration. The Knight is engaged in the often toilsome, routine efforts required to realise the dreams of his heart. He is building the foundations to support his dreams and his goals."),
                       Tarot(tarotName: "Queen Of Pentacles", tarotImage: UIImage(named: ("rwqueenpentacles.png"))!, tarotDescription: "The Queen of Pentacles depicts a solitary woman who sits upon a throne decorated with carvings of fruit trees, goats, angels, and other symbols of material success and sensual pleasure. The tree above her and the ground beneath her feet are rich with flowers and ripe plants of all sorts and she holds in her hand a single golden pentacle, which represents her material richness. At the very lower right-hand corner of the card a rabbit, the symbol of reproduction and fertility, leaps out from behind some bushes. The rabbit also hops into our awareness, symbolising that it is a good time to look before we leap and exercise good judgement as the Queen of Pentacles does."),
                       Tarot(tarotName: "King Of Pentacles", tarotImage: UIImage(named: ("rwkingpentacles.png"))!, tarotDescription: "The King of Pentacles is a card of worldly success, ultimate fulfilment, material satisfaction, and high ambition. The King sits upon a throne decorated with carvings of bulls and vines and his robe is covered with embroidered grapevines rich with fruit. He appears very regal and sophisticated. At his feet and all around him are vines, flowers, and plants of all sorts, representing the highest attainment of material success. In his right hand, he holds the sceptre of his power and in his left he holds a golden coin, symbolic of his material influence. Behind him is his castle, a symbol of all he has built through his efforts and determination. This King is therefore very serious about financial security and has made the accumulation of funds his main preoccupation in life. He is very proud of his achievements and willing to show others his prized possessions."),
                      
                      
                      Tarot(tarotName: "Ace Of Swords", tarotImage: UIImage(named: ("rwaceswords.png"))!, tarotDescription: "The Ace of Swords shows a hand, cloaked in white, holding an upright sword, symbolic of the mind and the intellect. At the tip of the sword is a wreath, indicating success and victory, and a crown, indicating mental clarity. However, the barren, mountainous landscape below the sword reflects the often cold nature of intellect."),
                       Tarot(tarotName: "Two Of Swords", tarotImage: UIImage(named: ("rw02swords.png"))!, tarotDescription: "The Two of Swords depicts a young, blindfolded woman who holds a sword in each hand. She sits before a sea filled with rocks and crags that present obstacles to ships which need clear passage. The blindfold shows that the woman in this card is confused about her situation and that she can see neither the problem nor the solution clearly. The swords she holds are perfectly balanced, showing a balanced and stable mind, and that both sides of the situation need to be addressed. The crossed swords are also symbolic of the need for a truce and the Suit of Swords indicates that the problem at hand needs to be resolved using logic and intellect. The waxing moon to the right of the woman shows a new beginning arising out of the solutions found for this problem."),
                       Tarot(tarotName: "Three Of Swords", tarotImage: UIImage(named: ("rw03swords.png"))!, tarotDescription: "The Three of Swords is a simply illustrated card with a difficult message. A heart, suspended in the air, is pierced by three swords. The heart is symbolic of emotion and beauty, while the piercing swords reflect the ability of logic and power to harm the physical body and the emotions of a person. The sky is heavily clouded and rain pours down violently, representing a grim moment in time."),
                       Tarot(tarotName: "Four Of Swords", tarotImage: UIImage(named: ("rw04swords.png"))!, tarotDescription: "The Four of Swords depicts the effigy of a knight lying upon a tomb. His hands are in the position of prayer and the tomb sits within a church. The stained glass behind the statue depicts a woman and child together. One sword lies beneath the knight, symbolising that there is only one key issue that is dominating your life at this time. Three further swords hang above him, pointing downwards."),
                       Tarot(tarotName: "Five Of Swords", tarotImage: UIImage(named: ("rw05swords.png"))!, tarotDescription: "In the Five of Swords, a young man, with a look of contempt on his face, stares at his conquered enemies. He possesses five swords, most of which he has taken from the other people in the card. The other two figures walk away from him slowly, with a sense of sadness and loss. The sky is cloudy and tumultuous, indicating that not all is well despite the battle being seemingly over."),
                       Tarot(tarotName: "Six Of Swords", tarotImage: UIImage(named: ("rw06swords.png"))!, tarotDescription: "The Six of Swords depicts a woman and a young child being rowed across a body of water towards a land that lies not far ahead. The woman’s head is covered, indicating sadness or loss as she moves away from something in her past. The water to the right of the boat is turbulent but the water to the left and near the land to which they are journeying is calm and steady. Although there is an indication of change or loss in the Six of Swords, and therefore a sense of moving away from something, there is also a sense of moving towards a more promising future. The calm waters in the distance suggest that the woman and child are now moving away from turmoil and conflict toward peace and tranquillity, even though they are both sad to leave behind their pasts. In the boat are six upright swords, symbolising the power of a rational mind over the heart and the intuition."),
                       Tarot(tarotName: "Seven Of Swords", tarotImage: UIImage(named: ("rw07swords.png"))!, tarotDescription: "The Seven of Swords shows a man sneaking away from a military camp with a bundle of five swords in his arms. Two other swords remain planted in the ground just behind him. His expression exhibits a sense of over-confidence and mocking, as though he felt absolutely sure of his success of getting away with the theft. However, in the distance a small group of soldiers can be seen to the left of the thief, and one of them holds a sword upraised. The thief has been found out!"),
                       Tarot(tarotName: "Eight Of Swords", tarotImage: UIImage(named: ("rw08swords.png"))!, tarotDescription: "The Eight of Swords shows a woman tied up, blindfolded, and surrounded by swords that act as a kind of prison or enclosure. It appears that there is no possibility of escape. She appears isolated and alone as she stands in the midst of a barren, watery wasteland far from the town in the distance. The sky is grey and cloudy, indicating despair and a lack of hope. The woman’s feet do not touch the water, indicating that the feeling of being restricted in the Eight of Swords is based on an intellectual assessment of the situation and not an emotional one. There is a path cleared before her, so there is actually a way out of this situation but the blindfolds prevent the woman from seeing her way out."),
                       Tarot(tarotName: "Nine Of Swords", tarotImage: UIImage(named: ("rw09swords.png"))!, tarotDescription: "The Nine of Swords shows a woman with her head in her hands, sitting up in her bed. She appears to have just woken up from a bad nightmare, and is obviously upset, fearful and anxious following her dream. Nine swords hang on the wall behind her and the base of the bed is decorated with a carving of a duel in which one person is being defeated by another. The quilt covering the woman is decorated with roses and the outlines of astrological symbols."),
                       Tarot(tarotName: "Ten Of Swords", tarotImage: UIImage(named: ("rw10swords.png"))!, tarotDescription: "The Ten of Swords shows a man lying face down with ten long swords embedded in his back. A red cape is draped over the lower half of his body, while his top half remains unclothed. The sky above him is pitch black and there is a general feeling of pain, loss, and misfortune. However, despite these ominous images, there are positive aspects to this card. The sea before which the body lies is still and calm and the sun is rising in the distance beyond the mountains, indicating that the darkness will soon be dispelled. Thus, each new beginning must come from an end, and with every defeat are sown the seeds of future victory."),
                       Tarot(tarotName: "Page Of Swords", tarotImage: UIImage(named: ("rwpageswords.png"))!, tarotDescription: "The Page of Swords shows a young man standing in the midst of rough terrain with a sword held in both hands. The sky is filled with turbulent clouds and the trees in the background are obviously wind-blown, as is the young man’s hair. The waters behind the Page are rough and the general feeling of this card is one of tumultuous energy."),
                       Tarot(tarotName: "Knight Of Swords", tarotImage: UIImage(named: ("rwknightswords.png"))!, tarotDescription: "The Knight of Swords shows a young man in his armour riding a powerful white horse into the midst of a battle in the distance. The white colour of the horse symbolises the purity of the intellectual energy that motivates the rider. The sky behind him is filled with storm clouds and the trees are tossed wildly by the wind. The horse’s harness is decorated with images of butterflies and birds and the knight’s cape is also decorated with birds. He charges forward with great momentum and apparently without any regard to the dangers he may encounter."),
                       Tarot(tarotName: "Queen Of Swords", tarotImage: UIImage(named: ("rwqueenswords.png"))!, tarotDescription: "The Queen of Swords sits high on her throne with a stern look on her face indicating that no-one can fool her. In her right hand, she comfortably holds a sword pointed to the sky, and her left hand extends as if she has something to offer to others. Behind her is a spring sky, different from the winter settings on most other Swords cards, and this has an emergence and growth quality to it. The sky is clear, representing her clarity of mind as she considers matters of the intellect. The bird above her head symbolises the mind’s ability to soar above day-to-day issues in order to arrive at appropriate solutions."),
                       Tarot(tarotName: "King Of Swords", tarotImage: UIImage(named: ("rwkingswords.png"))!, tarotDescription: "The King of Swords sits upon his throne of command, holding a large upward-pointing, double-edged sword in his right hand, while his left hand rests gently upon his lap. On his left Saturn finger is a ring, symbolic of power and taking his responsibilities seriously. The King wears a blue tunic, symbolic of a desire for spiritual understanding, and a purple cape, symbolic of compassion combined with intellect. The back of his throne is decorated with butterflies (transformation), crescent moons and an angel just near his left ear, positioned as if to give him subtle guidance. The sky is relatively clear with a few clouds, representing general mental clarity. The trees in the background appear motionless and reflect the stern judgement of the King."),
                      
                      
                      Tarot(tarotName: "Ace Of Wands", tarotImage: UIImage(named: ("rwacewands.png"))!, tarotDescription: "In the Ace of Wands, a hand reaches out from a cloud, as if a spiritual opportunity or offering is being made, to grasp a wand that is still flowering, growing and developing. The leaves floating down with the wind signify material and spiritual progress and balance. In the distance on the left, there is a castle that represents the promise of what opportunities may come."),
                       Tarot(tarotName: "Two Of Wands", tarotImage: UIImage(named: ("rw02wands.png"))!, tarotDescription: "The man in the Two of Wands is holding a small globe and stands on the roof of a castle, looking out over a vast terrain to the right and an ocean to the left. The globe in his hands represents that the world is his oyster and there is huge potential if he can expand his horizons to encompass broader life experiences. He understands his ambition and knows what must be done. He is wearing an orange tunic, which symbolises an enthusiastic approach to life, and a red hat, symbolising a passion for adventure."),
                       Tarot(tarotName: "Three Of Wands", tarotImage: UIImage(named: ("rw03wands.png"))!, tarotDescription: "On the Three of Wands, a man stands on a cliff, with his back turned, looking out over the sea to distant mountains. From this height, he can see all that lies ahead and is aware of the impending challenges and opportunities. The three Wands surrounding him are firmly planted in the ground, reflecting his commitment to his future plans."),
                       Tarot(tarotName: "Four Of Wands", tarotImage: UIImage(named: ("rw04wands.png"))!, tarotDescription: "In the Four of Wands, a couple dances beneath a welcome wreath, tied between four crystal tipped wands. The canopy of flowers on the four wands is also similar to the wedding canopy or chuppah of the traditional Jewish ceremony and thus represents a time of fulfilment and satisfaction at the attainment of a goal. In the background stand another group of people, just in front of a large castle, also decorated in flowers. It appears as if a celebration is being held, perhaps as a homecoming or a celebration from within the castle."),
                       Tarot(tarotName: "Five Of Wands", tarotImage: UIImage(named: ("rw05wands.png"))!, tarotDescription: "In the Five of Wands, five men wave around their wands chaotically without any regard for each other and appear to be in direct competition with each other and engaged in conflict. However, on closer observation, their wands are only raised and are not striking anyone. It is possible that they are actually enjoying themselves in this chaos with no real intent to harm anyone. The men wear different coloured clothes to symbolise the various backgrounds and belief systems that are held by the world’s populations."),
                       Tarot(tarotName: "Six Of Wands", tarotImage: UIImage(named: ("rw06wands.png"))!, tarotDescription: "The Six of Wands depicts a man wearing a victory wreath around his head, riding a white horse through a crowd of cheering people. The white horse represents strength, purity, and the success of an adventure, and the crowd of people demonstrates public recognition for the man’s achievements. The wand held by the rider also has a wreath tied to it, further emphasising success and achievement. He is not afraid to show off to others what he has accomplished in his life so far, and even better, the people around him cheer him along."),
                       Tarot(tarotName: "Seven Of Wands", tarotImage: UIImage(named: ("rw07wands.png"))!, tarotDescription: "In the Seven of Wands, a man stands on top of a hill and is challenged below by opponents that want what he has, success and status. The man appears to be in a defensive position, fiercely retaliating against those who attack him and defending his position as ‘king of the hill’. Interestingly, the man is wearing two different shoes, suggesting that he may have uneven footing or may be unclear of his own stance."),
                       Tarot(tarotName: "Eight Of Wands", tarotImage: UIImage(named: ("rw08wands.png"))!, tarotDescription: "The Eight of Wands shows eight blossoming wands hurtling through the air at a great pace. The flight of the wands suggests change, movement and travel. The background is clear, indicating that there is now little that stands in your way, and there is a beautiful river flowing freely and giving life to the landscape around it."),
                       Tarot(tarotName: "Nine Of Wands", tarotImage: UIImage(named: ("rw09wands.png"))!, tarotDescription: "The Nine of Wands shows a weary, injured man who holds a staff as though in a posture of final defence. He has fought the battle and won. He is protected by a number of wands behind him that appear like a wall around him. He appears drained and exhausted as he leans on his wand but he is ready to go to battle again. He has the look of determination in his eye to overcome this final challenge and reach a point of accomplishment and victory. He stands up for what he believes in and holds firm in those beliefs."),
                       Tarot(tarotName: "Ten Of Wands", tarotImage: UIImage(named: ("rw10wands.png"))!, tarotDescription: "The Ten of Wands shows a man carrying a very heavy bundle of wands or sticks. He appears to be over-burdened with the weight, yet he knows he is not far away from the town he is walking towards. This card appears to indicate someone who has just finished a harvest and is struggling to bring the fruits of his labours to the local market."),
                       Tarot(tarotName: "Page Of Wands", tarotImage: UIImage(named: ("rwpagewands.png"))!, tarotDescription: "The Page of Wands is a well-dressed young man who stands alone in the midst of a barren wilderness, talking out loud of his dreams and desires. This scene indicates that much of the Page’s creative energy is still very much only a potential or, at best, only an idea. He holds his staff upwards and looks to it with confidence. His shirt is covered with the design of salamanders, a mythical creature that is associated with fire and transformation."),
                       Tarot(tarotName: "Knight Of Wands", tarotImage: UIImage(named: ("rwknightwands.png"))!, tarotDescription: "The Knight of Wands is seen riding upon his horse, which rears up in the intensity of the Knight’s quest for success. The Knight’s face bears the determination of one bound to succeed. The plumes from the Knight of Wands’ helmet and the decorative tassels hanging from his back and arms are the colour of flame and he, like the Page, wears a shirt covered with the symbol of the fiery salamander."),
                       Tarot(tarotName: "Queen Of Wands", tarotImage: UIImage(named: ("rwqueenwands.png"))!, tarotDescription: "The Queen sits upon her throne that is decorated with lions facing opposing direction, a symbol of fire and strength. In her left hand and behind her are sunflowers, symbolising life, fertility, joy and satisfaction. In her right hand is a wand which is beginning to blossom with life. In these positive aspects, the Queen of Wands represents fidelity, warmth, and sustenance. However, at her feet is a black cat, a symbol of the darker, lesser known side of this Queen. Black cats are typically associated with magic and occultism. The cat expresses the independent nature of this Queen and her interest in occult powers and the energy of magic. There are other theories on what the cat symbolises, but as with all symbolism, the true 'meaning' is up to the observer."),
                       Tarot(tarotName: "King Of Wands", tarotImage: UIImage(named: ("rwkingwands.png"))!, tarotDescription: "The King of Wands holds a blossoming wand in his hand, representing life and creativity. His throne and cape are decorated with the lion and the salamander, symbols of fire and strength. The salamanders biting their own tails represent infinity and the ongoing drive to move forward against all obstacles. His robe is bright orange like a flame, and his crown has the shape of tongues of fire.")]
    
    var cardsDrawnArray: [UIImage] = []
    
    @IBOutlet weak var segmentedControl: UISegmentedControl!
    @IBOutlet weak var tarotCardOne: UIImageView!
    @IBOutlet weak var tarotCardTwo: UIImageView!
    @IBOutlet weak var tarotCardThree: UIImageView!
    @IBOutlet weak var tarotCardFour: UIImageView!
    @IBOutlet weak var tarotCardFive: UIImageView!
    @IBOutlet weak var tarotCardSix: UIImageView!
    @IBOutlet weak var tarotCardSeven: UIImageView!
    @IBOutlet weak var tarotCardEight: UIImageView!
    @IBOutlet weak var tarotCardNine: UIImageView!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view.
        
    }
    
    override func viewWillAppear(_ animated: Bool) {
        segmentedControl.selectedSegmentIndex = 0
        oneCardDrawn()
    }
    
    var cardsDrawn = 0
    
    func oneCardDrawn() {
        
        cardsDrawn = 1
        tarotCardOne.isHidden = true
        tarotCardTwo.isHidden = true
        tarotCardThree.isHidden = true
        tarotCardFour.isHidden = true
        tarotCardFive.isHidden = false
        tarotCardFive.image = #imageLiteral(resourceName: "Back")
        tarotCardSix.isHidden = true
        tarotCardSeven.isHidden = true
        tarotCardEight.isHidden = true
        tarotCardNine.isHidden = true
        
    }
    
    func threeCardsDrawn() {
        
        cardsDrawn = 3
        tarotCardOne.isHidden = true
        tarotCardTwo.isHidden = true
        tarotCardThree.isHidden = true
        tarotCardFour.isHidden = false
        tarotCardFour.image = #imageLiteral(resourceName: "Back")
        tarotCardFive.isHidden = false
        tarotCardFive.image = #imageLiteral(resourceName: "Back")
        tarotCardSix.isHidden = false
        tarotCardSix.image = #imageLiteral(resourceName: "Back")
        tarotCardSeven.isHidden = true
        tarotCardEight.isHidden = true
        tarotCardNine.isHidden = true
        
    }
    
    func fiveCardsDrawn() {
        
        cardsDrawn = 5
        tarotCardOne.isHidden = true
        tarotCardTwo.isHidden = false
        tarotCardTwo.image = #imageLiteral(resourceName: "Back")
        tarotCardThree.isHidden = true
        tarotCardFour.isHidden = false
        tarotCardFour.image = #imageLiteral(resourceName: "Back")
        tarotCardFive.isHidden = false
        tarotCardFive.image = #imageLiteral(resourceName: "Back")
        tarotCardSix.isHidden = false
        tarotCardSix.image = #imageLiteral(resourceName: "Back")
        tarotCardSeven.isHidden = true
        tarotCardEight.isHidden = false
        tarotCardEight.image = #imageLiteral(resourceName: "Back")
        tarotCardNine.isHidden = true
        
    }
    
    func nineCardsDrawn() {
        
        cardsDrawn = 9
        tarotCardOne.isHidden = false
        tarotCardOne.image = #imageLiteral(resourceName: "Back")
        tarotCardTwo.isHidden = false
        tarotCardTwo.image = #imageLiteral(resourceName: "Back")
        tarotCardThree.isHidden = false
        tarotCardThree.image = #imageLiteral(resourceName: "Back")
        tarotCardFour.isHidden = false
        tarotCardFour.image = #imageLiteral(resourceName: "Back")
        tarotCardFive.isHidden = false
        tarotCardFive.image = #imageLiteral(resourceName: "Back")
        tarotCardSix.isHidden = false
        tarotCardSix.image = #imageLiteral(resourceName: "Back")
        tarotCardSeven.isHidden = false
        tarotCardSeven.image = #imageLiteral(resourceName: "Back")
        tarotCardEight.isHidden = false
        tarotCardEight.image = #imageLiteral(resourceName: "Back")
        tarotCardNine.isHidden = false
        tarotCardNine.image = #imageLiteral(resourceName: "Back")
        
    }
    
    @IBAction func castType(_ sender: Any) {
        
        switch segmentedControl.selectedSegmentIndex {
        case 0:
            oneCardDrawn()
        case 1:
            threeCardsDrawn()
        case 2:
            fiveCardsDrawn()
        case 3:
            nineCardsDrawn()
        default: break
        }
        
    }
    
    @IBAction func drawCardsButtonPressed(_ sender: Any) {
        
        cardsDrawnArray = []
        
        if cardsDrawn == 1 {
            
            let randomCards = cardsArray[Int(arc4random_uniform(UInt32(cardsArray.count)))]
            cardsDrawnArray.append(randomCards.tarotImage)
            
            tarotCardFive.image = cardsDrawnArray[0]
            
        } else if cardsDrawn == 3 {
            
            for _ in 0...2 {
                
                let randomCards = cardsArray[Int(arc4random_uniform(UInt32(cardsArray.count)))]
                cardsDrawnArray.append(randomCards.tarotImage)
                
            }
            
            tarotCardFour.image = cardsDrawnArray[0]
            tarotCardFive.image = cardsDrawnArray[1]
            tarotCardSix.image = cardsDrawnArray[2]
            
        }
            
        else if cardsDrawn == 5 {
            
            for _ in 0...4 {
                
                let randomCards = cardsArray[Int(arc4random_uniform(UInt32(cardsArray.count)))]
                cardsDrawnArray.append(randomCards.tarotImage)
            }
            
            tarotCardTwo.image = cardsDrawnArray[0]
            tarotCardFour.image = cardsDrawnArray[1]
            tarotCardFive.image = cardsDrawnArray[2]
            tarotCardSix.image = cardsDrawnArray[3]
            tarotCardEight.image = cardsDrawnArray[4]
            
        }  else if cardsDrawn == 9 {
            
            for _ in 0...8 {
                
                let randomCards = cardsArray[Int(arc4random_uniform(UInt32(cardsArray.count)))]
                cardsDrawnArray.append(randomCards.tarotImage)
            }
            
            tarotCardOne.image = cardsDrawnArray[0]
            tarotCardTwo.image = cardsDrawnArray[1]
            tarotCardThree.image = cardsDrawnArray[2]
            tarotCardFour.image = cardsDrawnArray[3]
            tarotCardFive.image = cardsDrawnArray[4]
            tarotCardSix.image = cardsDrawnArray[5]
            tarotCardSeven.image = cardsDrawnArray[6]
            tarotCardEight.image = cardsDrawnArray[7]
            tarotCardNine.image = cardsDrawnArray[8]
            
        } else {
            print(" Invalid Number")
        }
        
    }
}

